# ds_auto_insights/export_utils.py

import os
import io
import base64
from datetime import datetime
from typing import List, Dict, Any, Optional
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from pathlib import Path
import streamlit as st
import markdown
from weasyprint import HTML, CSS


def export_chart_as_image(chart_info: Dict[str, Any], format: str = "png") -> bytes:
    """Export a single chart as an image (PNG/SVG)"""
    try:
        chart_type = chart_info.get('type')
        data = chart_info.get('data')
        title = chart_info.get('title', 'Chart')
        
        if chart_type == 'histogram':
            fig = px.bar(
                data, 
                x='bin_range', 
                y='count',
                title=title,
                template='plotly_white'
            )
        elif chart_type == 'bar':
            fig = px.bar(
                data, 
                x='category', 
                y='count',
                title=title,
                template='plotly_white'
            )
        elif chart_type == 'scatter':
            fig = px.scatter(
                data, 
                x=chart_info['x_column'], 
                y=chart_info['y_column'],
                color=chart_info.get('color_column'),
                title=title,
                template='plotly_white'
            )
        elif chart_type == 'line':
            fig = px.line(
                data, 
                x=chart_info['x_column'], 
                y=chart_info['y_column'],
                title=title,
                template='plotly_white'
            )
        else:
            raise ValueError(f"Unsupported chart type: {chart_type}")
        
        # Export as image
        if format.lower() == 'png':
            img_bytes = pio.to_image(fig, format='png', width=800, height=600)
        elif format.lower() == 'svg':
            img_bytes = pio.to_image(fig, format='svg', width=800, height=600)
        else:
            raise ValueError(f"Unsupported format: {format}")
            
        return img_bytes
        
    except Exception as e:
        st.error(f"Error exporting chart: {e}")
        return None


def generate_markdown_report(chat_history: List[Dict], dataset_name: str = "Dataset") -> str:
    """Generate a comprehensive Markdown report from chat history"""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    markdown_content = f"""# Data Analysis Report

**Dataset:** {dataset_name}  
**Generated:** {timestamp}  
**Tool:** DS Auto Insights

---

## Executive Summary

This report contains the analysis and insights generated from an interactive data exploration session. The analysis includes various visualizations and statistical findings that provide comprehensive insights into the dataset.

---

## Analysis Session

"""
    
    chart_counter = 1
    
    for i, msg in enumerate(chat_history):
        if msg["role"] == "user":
            markdown_content += f"\n### 🔍 Question {i//2 + 1}\n\n"
            markdown_content += f"{msg['content']}\n\n"
            
        elif msg["role"] == "assistant":
            markdown_content += f"### 💡 Analysis\n\n"
            markdown_content += f"{msg['content']}\n\n"
            
            # Add charts if they exist
            if "charts" in msg:
                for chart in msg["charts"]:
                    chart_title = chart.get('title', f'Chart {chart_counter}')
                    chart_type = chart.get('type', 'chart')
                    
                    markdown_content += f"#### 📊 {chart_title}\n\n"
                    markdown_content += f"*Chart Type:* {chart_type.title()}\n\n"
                    
                    # Add chart placeholder (will be replaced with actual image in PDF)
                    markdown_content += f"![{chart_title}](chart_{chart_counter}.png)\n\n"
                    chart_counter += 1
            
            markdown_content += "---\n\n"
    
    # Add footer
    markdown_content += f"""
## About This Report

This report was automatically generated by DS Auto Insights, a tool that enables natural language data analysis and visualization. All charts and insights were created through conversational queries with an AI-powered data analysis assistant.

**Report Generated:** {timestamp}  
**Tool Version:** DS Auto Insights v1.0
"""
    
    return markdown_content


def export_pdf_report(chat_history: List[Dict], dataset_name: str = "Dataset") -> bytes:
    """Generate a PDF report with embedded charts"""
    
    # Generate base markdown
    markdown_content = generate_markdown_report(chat_history, dataset_name)
    
    # Convert markdown to HTML
    html_content = markdown.markdown(markdown_content)
    
    # Create enhanced HTML with CSS styling
    styled_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Data Analysis Report - {dataset_name}</title>
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                line-height: 1.6;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                color: #333;
            }}
            h1 {{
                color: #1f2937;
                border-bottom: 3px solid #3b82f6;
                padding-bottom: 10px;
            }}
            h2 {{
                color: #374151;
                margin-top: 30px;
            }}
            h3 {{
                color: #4b5563;
                margin-top: 25px;
            }}
            h4 {{
                color: #6b7280;
                margin-top: 20px;
            }}
            code {{
                background-color: #f3f4f6;
                padding: 2px 4px;
                border-radius: 3px;
                font-family: 'SF Mono', Monaco, monospace;
            }}
            blockquote {{
                border-left: 4px solid #e5e7eb;
                margin: 0;
                padding-left: 20px;
                font-style: italic;
            }}
            .chart-placeholder {{
                width: 100%;
                height: 400px;
                background-color: #f9fafb;
                border: 2px dashed #d1d5db;
                border-radius: 8px;
                display: flex;
                align-items: center;
                justify-content: center;
                margin: 20px 0;
            }}
            hr {{
                border: 0;
                height: 1px;
                background: #e5e7eb;
                margin: 30px 0;
            }}
        </style>
    </head>
    <body>
        {html_content}
    </body>
    </html>
    """
    
    # Generate charts and embed them
    chart_counter = 1
    for msg in chat_history:
        if msg["role"] == "assistant" and "charts" in msg:
            for chart in msg["charts"]:
                try:
                    # Export chart as PNG
                    chart_bytes = export_chart_as_image(chart, format='png')
                    if chart_bytes:
                        # Convert to base64 for embedding
                        chart_b64 = base64.b64encode(chart_bytes).decode()
                        chart_data_uri = f"data:image/png;base64,{chart_b64}"
                        
                        # Replace placeholder with actual chart
                        styled_html = styled_html.replace(
                            f"chart_{chart_counter}.png",
                            chart_data_uri
                        )
                except Exception as e:
                    st.warning(f"Could not embed chart {chart_counter}: {e}")
                
                chart_counter += 1
    
    # Generate PDF
    try:
        pdf_bytes = HTML(string=styled_html).write_pdf()
        return pdf_bytes
    except Exception as e:
        st.error(f"Error generating PDF: {e}")
        return None


def create_narrative_summary(chat_history: List[Dict]) -> str:
    """Create an AI-generated narrative summary of the analysis"""
    
    # Extract key insights from the conversation
    insights = []
    charts_created = []
    
    for msg in chat_history:
        if msg["role"] == "assistant":
            # Extract key findings (simplified heuristic)
            content = msg["content"]
            if "correlation" in content.lower():
                insights.append("Correlation analysis was performed")
            if "distribution" in content.lower():
                insights.append("Data distribution was analyzed")
            if "top" in content.lower() and ("categories" in content.lower() or "values" in content.lower()):
                insights.append("Top categories were identified")
            
            # Count charts
            if "charts" in msg:
                charts_created.extend([chart.get('type') for chart in msg["charts"]])
    
    # Create narrative
    narrative = f"""## Key Insights Summary

This analysis session generated {len(insights)} key insights and {len(charts_created)} visualizations:

"""
    
    if insights:
        narrative += "**Analysis performed:**\n"
        for insight in insights:
            narrative += f"- {insight}\n"
        narrative += "\n"
    
    if charts_created:
        narrative += "**Visualizations created:**\n"
        chart_types = list(set(charts_created))
        for chart_type in chart_types:
            count = charts_created.count(chart_type)
            narrative += f"- {count} {chart_type} chart(s)\n"
        narrative += "\n"
    
    narrative += """**Recommendations:**
- Review the visualizations to identify patterns and outliers
- Consider the relationships discovered between variables
- Use these insights to inform business decisions
- Share this report with stakeholders for further discussion
"""
    
    return narrative


def export_session_data(chat_history: List[Dict], charts_data: List[Dict]) -> Dict[str, Any]:
    """Export session data as JSON for later analysis"""
    
    export_data = {
        "timestamp": datetime.now().isoformat(),
        "tool_version": "1.0",
        "session_data": {
            "chat_history": chat_history,
            "charts_metadata": [
                {
                    "type": chart.get("type"),
                    "title": chart.get("title"),
                    "columns": chart.get("x_column", "") + "," + chart.get("y_column", ""),
                } for chart in charts_data if chart
            ]
        }
    }
    
    return export_data
